#!/usr/bin/env bash
# Synthesizes the Career Archipelago sound kit — 7 mono Ogg files, CC0.
# Every sound is generated by ffmpeg filters; no third-party material.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p public/audio
OUT=public/audio

mono_ogg() { # helper: enforce mono/44.1k/vorbis q2
  ffmpeg -y -loglevel error "$@" -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2
}

echo "[1/7] wind.ogg — brown noise, lowpassed"
ffmpeg -y -loglevel error -f lavfi -i "anoisesrc=color=brown:r=44100:a=0.55:d=45" \
  -af "lowpass=f=400,lowpass=f=500,volume=0.9" \
  -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2 "$OUT/wind.ogg"

echo "[2/7] waterfall.ogg — bandpassed white noise"
ffmpeg -y -loglevel error -f lavfi -i "anoisesrc=color=white:r=44100:a=0.4:d=40" \
  -af "bandpass=f=1600:w=800,tremolo=f=0.3:d=0.25,volume=0.85" \
  -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2 "$OUT/waterfall.ogg"

# --- CONT1 ---
echo "[3/7] birds.ogg — sparse sine-sweep chirps over soft noise bed"
ffmpeg -y -loglevel error -f lavfi -i "anoisesrc=color=pink:r=44100:a=0.06:d=30" -f lavfi -i "sine=frequency=2400:sample_rate=44100:duration=30" \
  -filter_complex "[1]vibrato=f=6.5:d=0.9,tremolo=f=9:d=0.95,volume=0.5[b];[0][b]amix=inputs=2:duration=first:weights=1 0.35,volume=1.4" \
  -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2 "$OUT/birds.ogg"

echo "[4/7] night.ogg — pulsed highpass bursts + dark pad"
ffmpeg -y -loglevel error -f lavfi -i "anoisesrc=color=white:r=44100:a=0.25:d=45" -f lavfi -i "sine=frequency=110:sample_rate=44100:duration=45" \
  -filter_complex "[0]highpass=f=4200,tremolo=f=11:d=0.98,volume=0.5[c];[1]lowpass=f=200,volume=0.12[p];[c][p]amix=inputs=2:duration=longest,volume=1.1" \
  -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2 "$OUT/night.ogg"

# --- CONT2 ---
echo "[5/7] chime.ogg — warm bell (sine cluster, exponential decay)"
ffmpeg -y -loglevel error -f lavfi -i "sine=frequency=880:sample_rate=44100:duration=3" \
  -f lavfi -i "sine=frequency=1320:sample_rate=44100:duration=3" \
  -f lavfi -i "sine=frequency=1760:sample_rate=44100:duration=3" \
  -filter_complex "[0]volume=0.5[a];[1]volume=0.25[b];[2]volume=0.12[c];[a][b][c]amix=inputs=3,volume=1.6,afade=t=out:st=0.05:d=2.9:curve=exp" \
  -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2 "$OUT/chime.ogg"

echo "[6/7] achieve.ogg — two-note rising motif"
ffmpeg -y -loglevel error -f lavfi -i "sine=frequency=523.25:sample_rate=44100:duration=2" \
  -f lavfi -i "sine=frequency=783.99:sample_rate=44100:duration=2" \
  -filter_complex "[0]volume=0.45,afade=t=out:st=0.55:d=0.25[na];[1]adelay=600|600,volume=0.5,afade=t=out:st=1.15:d=0.6[nb];[na][nb]amix=inputs=2:normalize=0,volume=1.5" \
  -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2 "$OUT/achieve.ogg"

echo "[7/7] ui-tick.ogg — tiny blip"
ffmpeg -y -loglevel error -f lavfi -i "sine=frequency=1800:sample_rate=44100:duration=0.15" \
  -af "afade=t=in:st=0:d=0.005,afade=t=out:st=0.03:d=0.11,volume=0.6" \
  -ac 1 -ar 44100 -c:a libvorbis -qscale:a 2 "$OUT/ui-tick.ogg"

echo "=== AUDIO AUDIT ==="
TOTAL=0
for f in wind birds waterfall night chime achieve ui-tick; do
  FILE="$OUT/$f.ogg"
  CH=$(ffprobe -v error -select_streams a:0 -show_entries stream=channels -of csv=p=0 "$FILE")
  SZ=$(stat -c%s "$FILE")
  TOTAL=$((TOTAL + SZ))
  if [ "$CH" != "1" ]; then echo "FAIL: $f.ogg is not mono (channels=$CH)"; exit 1; fi
  printf "%-16s %6d bytes  mono=ok\n" "$f.ogg" "$SZ"
done
echo "TOTAL: $TOTAL bytes"
LIMIT=$((8 * 1024 * 1024))
if [ "$TOTAL" -gt "$LIMIT" ]; then echo "FAIL: exceeds 8MB budget"; exit 1; fi
echo "ALL OK — synthesized kit within budget"
